source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift3', :commit => '3cc5b4e8453bec9fd6b973d60e6b0605a38e4cf4'
pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage.git', :branch => 'swift3'

target 'WistiaKit_Example' do
  pod 'WistiaKit', :path => '../'
end

target 'WistiaKit_Tests' do
  pod 'WistiaKit', :path => '../'
end
